### ISSUE TITLE
SQLite package has not been found installed

### ISSUE THREAD

**Issue by soon530** [soon530/nestjs-study#30]
https://www.npmjs.com/package/sqlite#install-sqlite3
原來sqlite是typescript用的，而底層又去call sqlite3這套件。

```
[Nest] 11541  - 11/09/2022, 2:30:14 PM   ERROR [TypeOrmModule] Unable to connect to the database. Retrying (2)...
DriverPackageNotInstalledError: SQLite package has not been found installed. Try to install it: npm install sqlite3 --save
    at SqliteDriver.loadDependencies (/Users/vic/dev/nestjs-study/src/driver/sqlite/SqliteDriver.ts:180:19)
    at new SqliteDriver (/Users/vic/dev/nestjs-study/src/driver/sqlite/SqliteDriver.ts:49:14)
    at DriverFactory.create (/Users/vic/dev/nestjs-study/src/driver/DriverFactory.ts:44:24)
    at new DataSource (/Users/vic/dev/nestjs-study/src/data-source/DataSource.ts:139:43)
    at createTypeormDataSource (/Users/vic/dev/nestjs-study/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:172:23)
    at Function.<anonymous> (/Users/vic/dev/nestjs-study/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:190:42)
    at Generator.next (<anonymous>)
    at /Users/vic/dev/nestjs-study/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/vic/dev/nestjs-study/node_modules/@nestjs/typeorm/dist/typeorm-core.module.js:16:12)
```

**Comment by soon530** [comment]
安裝sqlite3套件。
```
 % yarn add sqlite3
yarn add v1.22.19
[1/4] 🔍  Resolving packages...
warning sqlite3 > node-gyp > make-fetch-happen > cacache > @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning " > swagger-ui-express@4.5.0" has unmet peer dependency "express@>=4.0.0".
warning " > ts-loader@9.4.1" has unmet peer dependency "webpack@^5.0.0".
[4/4] 🔨  Building fresh packages...
success Saved lockfile.
success Saved 51 new dependencies.
info Direct dependencies
└─ sqlite3@5.1.2
info All dependencies
├─ @gar/promisify@1.1.3
├─ @mapbox/node-pre-gyp@1.0.10
├─ @npmcli/fs@1.1.1
├─ @npmcli/move-file@1.1.2
├─ @tootallnate/once@1.1.2
├─ abbrev@1.1.1
├─ agent-base@6.0.2
├─ agentkeepalive@4.2.1
├─ aggregate-error@3.1.0
├─ aproba@2.0.0
├─ are-we-there-yet@2.0.0
├─ cacache@15.3.0
├─ chownr@2.0.0
├─ clean-stack@2.2.0
├─ color-support@1.1.3
├─ console-control-strings@1.1.0
├─ delegates@1.0.0
├─ detect-libc@2.0.1
├─ encoding@0.1.13
├─ env-paths@2.2.1
├─ err-code@2.0.3
├─ fs-minipass@2.1.0
├─ gauge@3.0.2
├─ has-unicode@2.0.1
├─ http-cache-semantics@4.1.0
├─ http-proxy-agent@4.0.1
├─ https-proxy-agent@5.0.1
├─ humanize-ms@1.2.1
├─ indent-string@4.0.0
├─ infer-owner@1.0.4
├─ is-lambda@1.0.1
├─ make-fetch-happen@9.1.0
├─ minipass-fetch@1.4.1
├─ minipass-pipeline@1.2.4
├─ minipass-sized@1.0.3
├─ minizlib@2.1.2
├─ node-addon-api@4.3.0
├─ node-gyp@8.4.1
├─ nopt@5.0.0
├─ npmlog@5.0.1
├─ p-map@4.0.0
├─ promise-inflight@1.0.1
├─ promise-retry@2.0.1
├─ retry@0.12.0
├─ set-blocking@2.0.0
├─ socks-proxy-agent@6.2.1
├─ sqlite3@5.1.2
├─ ssri@8.0.1
├─ unique-filename@1.1.1
├─ unique-slug@2.0.2
└─ wide-align@1.1.5
✨  Done in 9.51s.
```

**Comment by soon530** [comment]
在專案底下，自己就產生了sqlite了。
<img width="283" alt="image" src="https://user-images.githubusercontent.com/1287332/200759292-be2b487b-0a31-46ed-91a0-1faf643373ee.png">
